traits:
  Ruby: true
  PostgreSQL 15: true

include:
  - cider-ci/task-components/bundle-rspec-ruby.yml

scripts:

  show-db-env:
    body: |
      #!/usr/bin/env bash
      env | egrep '(^PG|^LEIHS_|^DATABASE_)' | sort

  database-configure-rails-db:
    start_when:
      gems are bundled:
        script_key: database-bundle-rspec-ruby
        states: [passed]
      showed-env:
        script_key: show-db-env
        states: [passed]
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_DATABASE_DIR
      ./bin/ruby cider-ci/scripts/configure-database.rb

  create-database:
    start_when:
      db-configured:
        script_key: database-configure-rails-db
        states: [passed]
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_DATABASE_DIR
      unset PGPORT
      unset PGUSER
      PGUSER="${PG15USER}" PGPORT="${PG15PORT}" ./bin/seeds-restore

  delete-database:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      unset PGPORT
      unset PGUSER
      dropdb -p "${PG15PORT}" -U "${PG15USER}" "$LEIHS_DATABASE_NAME"
    start_when:
      test is in terminal state:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]
      create-database is terminal:
        script_key: create-database
        states: [aborted, defective, passed, failed, skipped]

  test:
    start_when:
      database has been created:
        script_key: create-database
