source 'https://rubygems.org'

gem 'addressable'
gem 'base32-crockford'
gem 'exiftool_vendored'
gem 'factory_bot'
gem 'faker'
gem 'money-rails', '~> 1.4'
gem 'pg', platform: :mri
gem 'pg_tasks', git: 'https://github.com/drtom/rails_pg-tasks', branch: 'master_rails_5'
gem 'pry'
gem 'rails'
gem 'rspec'
gem 'sequel', '~> 4.42', '>= 4.42.1'
gem 'uuidtools'
