  --
  -- DO NOT EDIT
  -- 
  -- this file is automatically generated 
  -- it represents the current migration setatus but it is not the authoritative source
  --

--
-- PostgreSQL database dump
--


-- Dumped from database version 15.14 (Homebrew)
-- Dumped by pg_dump version 15.14 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: images; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: models; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: accessories; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: inventory_pools; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: accessories_inventory_pools; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: languages; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.languages (name, locale, "default", active) VALUES ('English (UK)', 'en-GB', true, true);
INSERT INTO public.languages (name, locale, "default", active) VALUES ('English (US)', 'en-US', false, true);
INSERT INTO public.languages (name, locale, "default", active) VALUES ('Deutsch', 'de-CH', false, true);
INSERT INTO public.languages (name, locale, "default", active) VALUES ('Züritüütsch', 'gsw-CH', false, true);
INSERT INTO public.languages (name, locale, "default", active) VALUES ('Castellano', 'es', false, false);
INSERT INTO public.languages (name, locale, "default", active) VALUES ('Français (CH)', 'fr-CH', false, false);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: api_tokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: buildings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.buildings (id, name, code) VALUES ('abae04c5-d767-425e-acc2-7ce04df645d1', 'general building', 'GB');


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.rooms (id, name, description, building_id, general) VALUES ('b8927fd2-014c-48c2-b095-fa1d5620debe', 'general room', NULL, 'abae04c5-d767-425e-acc2-7ce04df645d1', true);


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: authentication_systems; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.authentication_systems (id, name, description, type, enabled, priority, internal_private_key, internal_public_key, external_public_key, external_sign_in_url, send_email, send_org_id, send_login, shortcut_sign_in_enabled, created_at, updated_at, external_sign_out_url, sign_up_email_match) VALUES ('password', 'leihs password', NULL, 'password', true, 0, NULL, NULL, NULL, NULL, true, false, false, false, '2020-11-05 12:50:39.546594+00', '2020-11-05 12:50:39.546594+00', NULL, NULL);


--
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.groups (id, name, description, org_id, searchable, created_at, updated_at, admin_protected, system_admin_protected, organization) VALUES ('4dd87663-f731-5766-b97d-9494889ca66c', 'All users', NULL, 'all-users', 'All users all-users', '2021-03-08 10:02:51.767533+00', '2021-03-08 10:02:51.779113+00', true, true, 'leihs-core');


--
-- Data for Name: authentication_systems_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: authentication_systems_users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: contracts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: customer_orders; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: delegations_direct_users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: delegations_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: direct_access_rights; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: fields; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('inventory_code', true, 1, '{"type": "text", "group": null, "label": "Inventory Code", "required": true, "attribute": "inventory_code", "forPackage": true, "permissions": {"role": "inventory_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('serial_number', true, 4, '{"type": "text", "group": "General Information", "label": "Serial Number", "attribute": "serial_number", "permissions": {"role": "lending_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_mac_address', true, 5, '{"type": "text", "group": "General Information", "label": "MAC-Address", "attribute": ["properties", "mac_address"], "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_imei_number', true, 6, '{"type": "text", "group": "General Information", "label": "IMEI-Number", "attribute": ["properties", "imei_number"], "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('retired', true, 9, '{"type": "select", "group": "Status", "label": "Retirement", "values": [{"label": "No", "value": false}, {"label": "Yes", "value": true}], "default": false, "attribute": "retired", "forPackage": true, "permissions": {"role": "lending_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('retired_reason', true, 10, '{"type": "textarea", "group": "Status", "label": "Reason for Retirement", "required": true, "attribute": "retired_reason", "forPackage": true, "permissions": {"role": "lending_manager", "owner": true}, "visibility_dependency_value": "true", "visibility_dependency_field_id": "retired"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('is_inventory_relevant', true, 18, '{"type": "select", "group": "Inventory", "label": "Relevant for inventory", "values": [{"label": "No", "value": false}, {"label": "Yes", "value": true}], "default": true, "attribute": "is_inventory_relevant", "forPackage": true, "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('owner_id', true, 19, '{"type": "autocomplete", "group": "Inventory", "label": "Owner", "values": "all_inventory_pools", "attribute": ["owner", "id"], "forPackage": true, "permissions": {"role": "inventory_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('last_check', true, 20, '{"type": "date", "group": "Inventory", "label": "Last Checked", "default": "today", "attribute": "last_check", "forPackage": true, "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('inventory_pool_id', true, 21, '{"type": "autocomplete", "group": "Inventory", "label": "Responsible department", "values": "all_inventory_pools", "attribute": ["inventory_pool", "id"], "forPackage": true, "permissions": {"role": "inventory_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('responsible', true, 22, '{"type": "text", "group": "Inventory", "label": "Responsible person", "attribute": "responsible", "forPackage": true, "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('user_name', true, 23, '{"type": "text", "group": "Inventory", "label": "User/Typical usage", "attribute": "user_name", "forPackage": true, "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_reference', true, 24, '{"type": "radio", "group": "Invoice Information", "label": "Reference", "values": [{"label": "Running Account", "value": "invoice"}, {"label": "Investment", "value": "investment"}], "default": "invoice", "required": true, "attribute": ["properties", "reference"], "permissions": {"role": "inventory_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_project_number', true, 25, '{"type": "text", "group": "Invoice Information", "label": "Project Number", "required": true, "attribute": ["properties", "project_number"], "permissions": {"role": "inventory_manager", "owner": true}, "visibility_dependency_value": "investment", "visibility_dependency_field_id": "properties_reference"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('invoice_number', true, 26, '{"type": "text", "group": "Invoice Information", "label": "Invoice Number", "attribute": "invoice_number", "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('invoice_date', true, 27, '{"type": "date", "group": "Invoice Information", "label": "Invoice Date", "attribute": "invoice_date", "permissions": {"role": "lending_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('price', true, 28, '{"type": "text", "group": "Invoice Information", "label": "Initial Price", "currency": true, "attribute": "price", "forPackage": true, "permissions": {"role": "lending_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('supplier_id', true, 29, '{"type": "autocomplete", "group": "Invoice Information", "label": "Supplier", "values": "all_suppliers", "attribute": ["supplier", "id"], "extensible": true, "permissions": {"role": "lending_manager", "owner": true}, "extended_key": ["supplier", "name"]}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_warranty_expiration', true, 30, '{"type": "date", "group": "Invoice Information", "label": "Warranty expiration", "attribute": ["properties", "warranty_expiration"], "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_contract_expiration', true, 31, '{"type": "date", "group": "Invoice Information", "label": "Contract expiration", "attribute": ["properties", "contract_expiration"], "permissions": {"role": "lending_manager", "owner": true}, "target_type": "item"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_activation_type', true, 32, '{"type": "select", "group": "General Information", "label": "Activation Type", "values": [{"label": "None", "value": "none"}, {"label": "Dongle", "value": "dongle"}, {"label": "Serial Number", "value": "serial_number"}, {"label": "License Server", "value": "license_server"}, {"label": "Challenge Response/System ID", "value": "challenge_response"}], "default": "none", "attribute": ["properties", "activation_type"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_dongle_id', true, 33, '{"type": "text", "group": "General Information", "label": "Dongle ID", "required": true, "attribute": ["properties", "dongle_id"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license", "visibility_dependency_value": "dongle", "visibility_dependency_field_id": "properties_activation_type"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_license_type', true, 34, '{"type": "select", "group": "General Information", "label": "License Type", "values": [{"label": "Free", "value": "free"}, {"label": "Single Workplace", "value": "single_workplace"}, {"label": "Multiple Workplace", "value": "multiple_workplace"}, {"label": "Site License", "value": "site_license"}, {"label": "Concurrent", "value": "concurrent"}], "default": "free", "attribute": ["properties", "license_type"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_total_quantity', true, 35, '{"type": "text", "group": "General Information", "label": "Total quantity", "attribute": ["properties", "total_quantity"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_quantity_allocations', true, 36, '{"type": "composite", "group": "General Information", "label": "Quantity allocations", "attribute": ["properties", "quantity_allocations"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license", "data_dependency_field_id": "properties_total_quantity", "visibility_dependency_field_id": "properties_total_quantity"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_operating_system', true, 37, '{"type": "checkbox", "group": "General Information", "label": "Operating System", "values": [{"label": "Windows", "value": "windows"}, {"label": "Mac OS X", "value": "mac_os_x"}, {"label": "Linux", "value": "linux"}, {"label": "iOS", "value": "ios"}], "attribute": ["properties", "operating_system"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_installation', true, 38, '{"type": "checkbox", "group": "General Information", "label": "Installation", "values": [{"label": "Citrix", "value": "citrix"}, {"label": "Local", "value": "local"}, {"label": "Web", "value": "web"}], "attribute": ["properties", "installation"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_license_expiration', true, 39, '{"type": "date", "group": "General Information", "label": "License expiration", "attribute": ["properties", "license_expiration"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_maintenance_contract', true, 40, '{"type": "select", "group": "Maintenance", "label": "Maintenance contract", "values": [{"label": "No", "value": "false"}, {"label": "Yes", "value": "true"}], "default": "false", "attribute": ["properties", "maintenance_contract"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_maintenance_expiration', true, 41, '{"type": "date", "group": "Maintenance", "label": "Maintenance expiration", "attribute": ["properties", "maintenance_expiration"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license", "visibility_dependency_value": "true", "visibility_dependency_field_id": "properties_maintenance_contract"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_maintenance_currency', true, 42, '{"type": "select", "group": "Maintenance", "label": "Currency", "values": "all_currencies", "default": "CHF", "attribute": ["properties", "maintenance_currency"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license", "visibility_dependency_field_id": "properties_maintenance_expiration"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_maintenance_price', true, 43, '{"type": "text", "group": "Maintenance", "label": "Price", "currency": true, "attribute": ["properties", "maintenance_price"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license", "visibility_dependency_field_id": "properties_maintenance_currency"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('properties_procured_by', true, 44, '{"type": "text", "group": "Invoice Information", "label": "Procured by", "attribute": ["properties", "procured_by"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', true);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('attachments', true, 45, '{"type": "attachment", "group": "General Information", "label": "Attachments", "attribute": "attachments", "permissions": {"role": "lending_manager", "owner": true}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('model_id', true, 2, '{"type": "autocomplete-search", "group": null, "label": "Model", "required": true, "attribute": ["model", "id"], "form_name": "model_id", "value_attr": "id", "permissions": {"role": "lending_manager", "owner": false}, "search_attr": "search_term", "search_path": "models", "target_type": "item", "display_attr": "product", "display_attr_ext": "version", "item_value_label": ["model", "product"], "item_value_label_ext": ["model", "version"]}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('software_model_id', true, 3, '{"type": "autocomplete-search", "group": null, "label": "Software", "required": true, "attribute": ["model", "id"], "form_name": "model_id", "value_attr": "id", "permissions": {"role": "lending_manager", "owner": false}, "search_attr": "search_term", "search_path": "software", "target_type": "license", "display_attr": "product", "display_attr_ext": "version", "item_value_label": ["model", "product"], "item_value_label_ext": ["model", "version"]}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('name', true, 7, '{"type": "text", "group": "General Information", "label": "Name", "attribute": "name", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('note', true, 8, '{"type": "textarea", "group": "General Information", "label": "Note", "attribute": "note", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('is_broken', true, 11, '{"type": "radio", "group": "Status", "label": "Working order", "values": [{"label": "OK", "value": false}, {"label": "Broken", "value": true}], "default": false, "attribute": "is_broken", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('is_incomplete', true, 12, '{"type": "radio", "group": "Status", "label": "Completeness", "values": [{"label": "OK", "value": false}, {"label": "Incomplete", "value": true}], "default": false, "attribute": "is_incomplete", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('is_borrowable', true, 13, '{"type": "radio", "group": "Status", "label": "Borrowable", "values": [{"label": "OK", "value": true}, {"label": "Unborrowable", "value": false}], "default": false, "attribute": "is_borrowable", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('status_note', true, 14, '{"type": "textarea", "group": "Status", "label": "Status note", "attribute": "status_note", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('building_id', true, 15, '{"type": "autocomplete", "group": "Location", "label": "Building", "values": "all_buildings", "required": true, "attribute": ["room", "building_id"], "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item", "exclude_from_submit": true}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('room_id', true, 16, '{"type": "autocomplete", "group": "Location", "label": "Room", "required": true, "attribute": "room_id", "forPackage": true, "values_url": "/manage/rooms.json?building_id=$$$parent_value$$$", "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item", "values_label_method": "to_s", "values_dependency_field_id": "building_id"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('shelf', true, 17, '{"type": "text", "group": "Location", "label": "Shelf", "attribute": "shelf", "forPackage": true, "permissions": {"role": "lending_manager", "owner": false}, "target_type": "item"}', false);
INSERT INTO public.fields (id, active, "position", data, dynamic) VALUES ('license_version', true, 3, '{"type": "text", "group": null, "label": "License Version", "attribute": ["item_version"], "permissions": {"role": "inventory_manager", "owner": true}, "target_type": "license"}', false);


--
-- Data for Name: disabled_fields; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: emails; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: entitlement_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: entitlement_groups_direct_users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: entitlement_groups_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: entitlements; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: favorite_models; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: group_access_rights; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: groups_users; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: holidays; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: model_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: inventory_pools_model_groups; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: mail_templates; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('98757b9e-9891-4363-b74f-3a2110931195', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.691262', '2025-02-13 10:06:19.745002', true, 'order', 'en-GB', '[leihs] Order received');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('2865004b-00b4-4815-a4f6-4f39c48617bf', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.69381', '2025-02-13 10:06:19.746115', true, 'order', 'en-US', '[leihs] Order received');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('00f6c4fa-9d85-4736-a51b-54a890d0d492', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.696546', '2025-02-13 10:06:19.747199', true, 'order', 'de-CH', '[leihs] Bestellung eingetroffen');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('745ab92c-0ec1-41ec-896a-5e06a0cc1c68', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.774905', '2025-02-13 10:06:19.765143', true, 'order', 'es', '[leihs] Orden recibida');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('4b949422-52c9-497b-b7a9-c726a64c5e66', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.7778', '2025-02-13 10:06:19.765902', true, 'order', 'fr-CH', '[leihs] Commande reçue');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('01841af3-fc44-4b43-8e44-f9b8edbf1c42', NULL, 'received', 'text', 'Dear leihs manager,

** This is an automatically generated response **

An order for the following items listed below was received in an inventory pool you are responsible for.

Inventory pool: {{ inventory_pool.name }}
User: {{ user.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

This order is still pending. Please log in to your leihs system and either approve or reject it.

The user who placed this order has received a similar e-mail message informing them that the order first needs to be approved before it is valid.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.699276', '2025-02-13 10:06:19.748695', true, 'order', 'gsw-CH', '[leihs] Bschtelig aachoo');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('91b0fff1-1264-429a-ba5c-a628641bf2b5', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.66507', '2025-02-13 10:06:19.734443', true, 'user', 'en-GB', '[leihs] Reminder');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('6d22d1c8-38ad-4be0-8b03-7dada8ee0e03', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.672173', '2025-02-13 10:06:19.736967', true, 'user', 'en-US', '[leihs] Reminder');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('872a30d5-b0c9-4100-b915-8d83445191e4', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.675096', '2025-02-13 10:06:19.738202', true, 'user', 'de-CH', '[leihs] Erinnerung');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('76041eb2-061a-4aa9-8d32-3c4327dad7b2', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.738895', '2025-02-13 10:06:19.759924', true, 'user', 'es', '[leihs] Recordatorio');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('3a0a7b70-e1a2-45b7-824e-4bc5ae89c757', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.742412', '2025-02-13 10:06:19.762335', true, 'user', 'fr-CH', '[leihs] Rappel');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('1399c847-28bf-4778-9584-2127fd17733d', NULL, 'reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are overdue or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

Since we did not receive any request for renewal, we consequently demand the return of the items without further delay.

By not returning these items, you are blocking other people''s reservations. This is very unfair to the other clients and to the inventory manager, since you are causing a significant amount of trouble and annoyance.

You might receive an admonishment and be subject to late fees as well as the restriction of borrowing privileges. In case of recurrence you might be barred from the reservation system for up to 6 months.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.677886', '2025-02-13 10:06:19.739346', true, 'user', 'gsw-CH', '[leihs] Erinnerig');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('a3248d8a-c153-4573-bb8e-f81238c48542', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.716005', '2025-02-13 10:06:19.753337', true, 'order', 'en-GB', '[leihs] Reservation Confirmation');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('cc3ca99d-5d08-4816-a7f8-1d464c60e338', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.730452', '2025-02-13 10:06:19.754193', true, 'order', 'en-US', '[leihs] Reservation Confirmation');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('bc72996d-d639-436d-940a-47c0e60aceec', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.733687', '2025-02-13 10:06:19.755091', true, 'order', 'de-CH', '[leihs] Reservationsbestätigung');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('2b265bcf-cd7e-490f-a22f-dec80ed72520', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.795054', '2025-02-13 10:06:19.768302', true, 'order', 'es', '[leihs] Reserva Confirmada');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('6c2d9bc7-b50e-40c8-ade9-64180960259a', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.797556', '2025-02-13 10:06:19.769089', true, 'order', 'fr-CH', '[leihs] Confirmation de réservation');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('99d4cb9b-abbf-4629-9c14-31275d8e0c91', NULL, 'approved', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items has been confirmed by the inventory manager:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{% if comment %}

These are the comments of the inventory manager:

{{ comment }}

{% endif %}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.736548', '2025-02-13 10:06:19.755933', true, 'order', 'gsw-CH', '[leihs] Reservationsbeschtätigung');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('6d6ec0f8-eda3-404f-b0dd-a8d9c0f68bd2', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.739877', '2025-02-13 10:06:19.756709', true, 'order', 'en-GB', '[leihs] Reservation Rejected');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('30bed262-6deb-44c0-a8ea-4d5bb4ca3b1f', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.742632', '2025-02-13 10:06:19.757495', true, 'order', 'en-US', '[leihs] Reservation Rejected');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('2b8655ee-a6c9-4468-91f0-7b0268d5506c', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.745393', '2025-02-13 10:06:19.758263', true, 'order', 'de-CH', '[leihs] Reservation abgelehnt');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('3ef10a4c-c101-4553-8757-2e8c4f3491b7', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.804802', '2025-02-13 10:06:19.760751', true, 'order', 'es', '[leihs] Reserva Rechazada');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('78b63877-30f7-4811-a9f8-ba75b0907637', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.807154', '2025-02-13 10:06:19.761533', true, 'order', 'fr-CH', '[leihs] Réservation refusée');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('4025675b-11cf-4c00-8515-faa63fcffd90', NULL, 'rejected', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order was rejected for the following reason:

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

{{ comment }}

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.748278', '2025-02-13 10:06:19.759106', true, 'order', 'gsw-CH', '[leihs] Reservation abglehnt');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('17570c6d-5888-409f-bfbb-49d667fb7dda', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.702694', '2025-02-13 10:06:19.749686', true, 'order', 'en-GB', '[leihs] Reservation Submitted');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('5f75b6d3-60dd-4693-bff1-a055282b11b1', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.705521', '2025-02-13 10:06:19.75064', true, 'order', 'en-US', '[leihs] Reservation Submitted');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('09a59f8c-97ad-4b66-9b82-da9423822046', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.708533', '2025-02-13 10:06:19.751591', true, 'order', 'de-CH', '[leihs] Reservation abgeschickt');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('b7627dae-be7c-45a3-b614-b44f0efaee80', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.785684', '2025-02-13 10:06:19.76671', true, 'order', 'es', '[leihs] Reserva Presentada');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('e4eea6ad-2272-4faa-91d8-eb8c986b91c0', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.787875', '2025-02-13 10:06:19.767495', true, 'order', 'fr-CH', '[leihs] Réservation envoyée');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('96f1bfd3-fb9e-4489-ac8e-2135c685034d', NULL, 'submitted', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

Your order for the following items listed below was successfully submitted.

Inventory pool: {{ inventory_pool.name }}

{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }}, {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

Purpose:
{{ purpose }}

Unfortunately your order is still pending, but you will soon receive a confirmation of order by separate e-mail. You can view the status of your order through your leihs account.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.711856', '2025-02-13 10:06:19.752447', true, 'order', 'gsw-CH', '[leihs] Reservation abgschickt');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('a1bb0ddf-e1df-42ad-9dbd-ce6978af3a8e', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.681011', '2025-02-13 10:06:19.740475', true, 'user', 'en-GB', '[leihs] Some items should be returned tomorrow');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('f305ada7-3a1c-4171-9e7a-27b417978fc4', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.683518', '2025-02-13 10:06:19.741591', true, 'user', 'en-US', '[leihs] Some items should be returned tomorrow');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('8cf51778-26ac-4cae-af42-2c769b95b639', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.685905', '2025-02-13 10:06:19.7428', true, 'user', 'de-CH', '[leihs] Einige Gegenstände sollten morgen zurückgebracht werden');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('5a200443-d0fd-4a8c-8417-29593bb565af', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.748175', '2025-02-13 10:06:19.763569', true, 'user', 'es', '[leihs] Algunos elementos deberían de ser devueltos mañana');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('21fea574-3e8a-4bb9-8c73-26faa809bada', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2022-08-19 10:02:17.749979', '2025-02-13 10:06:19.764358', true, 'user', 'fr-CH', '[leihs] Des éléments doivent être retourné demain');
INSERT INTO public.mail_templates (id, inventory_pool_id, name, format, body, created_at, updated_at, is_template_template, type, language_locale, subject) VALUES ('29f61894-ffa8-41d1-a3f4-031448e25c89', NULL, 'deadline_soon_reminder', 'text', 'Dear {{ user.name }},

** This is an automatically generated response **

The following items are due to be returned tomorrow or need to be inspected:

{{ quantity }} item(s) due on {{ due_date | date: ''%d/%m/%Y'' }} at the inventory pool {{ inventory_pool.name }}
{% for l in reservations %}
* {{ l.quantity }} {{ l.model_name }} ({{ l.item_inventory_code }}), {{ l.start_date | date: ''%d/%m/%Y'' }} - {{ l.end_date | date: ''%d/%m/%Y'' }}
{% endfor %}

== Are any of the above items your personal computer?

We kindly ask you to contact us as soon as possible. Your computer might need an update.

== "Are any of the above borrowed items?

We are just sending you this little reminder because someone else is already waiting for some of these items.

In the interest of all our clients we ask you to observe the return dates.

Kind regards,

{{ email_signature }}

--
{{ inventory_pool.name }}
{{ inventory_pool.contact }}

Our opening times are as follows:
{{ inventory_pool.workdays }}

Please take note of our planned holidays:
{{ inventory_pool.holidays }}

{{ inventory_pool.description }}
', '2021-04-21 11:18:46.688424', '2025-02-13 10:06:19.743907', true, 'user', 'gsw-CH', '[leihs] Einige Sache sötted morn zruggbracht werde');


--
-- Data for Name: model_group_links; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: model_links; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: models_compatibles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: ms365_mailboxes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: ms365_mailboxes_aliases; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: options; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_admins; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_budget_periods; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_main_categories; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_categories; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_organizations; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_templates; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_requests; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_attachments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_budget_limits; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_category_inspectors; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_category_viewers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_images; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_requesters_organizations; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_requests_counters; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_settings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_uploads; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: procurement_users_filters; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: properties; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.settings (local_currency_string, contract_lending_party_string, email_signature, user_image_url, ldap_config, logo_url, time_zone, text, timeout_minutes, custom_head_tag, documentation_link, id, created_at, updated_at, lending_terms_acceptance_required_for_order, lending_terms_url, include_customer_email_in_contracts, show_contact_details_on_customer_order, home_page_image_url) VALUES ('GBP', NULL, 'Cheers,', NULL, NULL, NULL, 'Bern', NULL, 30, NULL, NULL, 0, '2020-11-05 12:50:29.190792+00', '2020-11-05 12:50:29.190792+00', false, NULL, false, false, NULL);


--
-- Data for Name: smtp_settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.smtp_settings (id, enabled, address, authentication_type, default_from_address, domain, enable_starttls_auto, openssl_verify_mode, password, port, sender_address, username, ms365_enabled, ms365_client_id, ms365_tenant_id, ms365_client_secret) VALUES (0, false, 'localhost', 'plain', 'your.lending.desk@example.com', 'localhost', false, 'none', NULL, 25, NULL, NULL, false, NULL, NULL, NULL);


--
-- Data for Name: suspensions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: system_and_security_settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.system_and_security_settings (id, accept_server_secret_as_universal_password, external_base_url, sessions_force_secure, sessions_force_uniqueness, sessions_max_lifetime_secs, instance_element, public_image_caching_enabled) VALUES (0, true, NULL, false, false, 432000, NULL, true);


--
-- Data for Name: user_password_resets; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: user_sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: workdays; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- PostgreSQL database dump complete
--


