#!/usr/bin/env bash

set -eux

LEIHS_DATABASE_NAME=${LEIHS_DATABASE_NAME:-leihs_seeds}

psql -c "DROP DATABASE IF EXISTS \"$LEIHS_DATABASE_NAME\";"
createdb $LEIHS_DATABASE_NAME
psql -d $LEIHS_DATABASE_NAME -f db/structure.sql
./scripts/restore-seeds
