#!/usr/bin/env bash

set -eux

LEIHS_DATABASE_NAME=${LEIHS_DATABASE_NAME:-leihs_seeds}

pg_dump -a $LEIHS_DATABASE_NAME \
  --column-inserts \
  --disable-triggers \
  --no-owner \
  -T schema_migrations \
  -T audited_changes \
  -T audits \
  -T ar_internal_metadata \
  > db/seeds.sql
