#!/usr/bin/env bash

PROJECT_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" ; cd .. > /dev/null 2>&1 && pwd -P)"


set -eux

LEIHS_DATABASE_NAME=${LEIHS_DATABASE_NAME:-leihs_seeds}

psql --quiet -d $LEIHS_DATABASE_NAME -f $PROJECT_DIR/db/seeds.sql -1 > /dev/null # 2>&1
