#!/usr/bin/env bash

set -eux

SCRIPT_DIR=$(dirname "$0")
DATABASE_NAME=${DATABASE_NAME:-leihs_seeds}

psql -d $DATABASE_NAME -c 'ALTER TABLE languages DISABLE TRIGGER trigger_check_exactly_one_default_language;'
psql -d $DATABASE_NAME -c 'ALTER TABLE fields DISABLE TRIGGER fields_insert_check_trigger;'
psql -d $DATABASE_NAME -c 'ALTER TABLE authentication_systems DISABLE TRIGGER audited_change_on_authentication_systems;'

psql -d $DATABASE_NAME -f $SCRIPT_DIR/../db/seeds.sql -1

psql -d $DATABASE_NAME -c 'ALTER TABLE languages ENABLE TRIGGER trigger_check_exactly_one_default_language;'
psql -d $DATABASE_NAME -c 'ALTER TABLE fields ENABLE TRIGGER fields_insert_check_trigger;'
psql -d $DATABASE_NAME -c 'ALTER TABLE authentication_systems ENABLE TRIGGER audited_change_on_authentication_systems;'
